### ISSUE TITLE
求 commodity 微服务Resource下的static前端静态资源

### ISSUE THREAD

**Issue by YR-9527** [EXsYang/hspedu_hspliving2#1]
大哥，能把Resource的静态资源传上来吗，求求了，找了好多天没找到，谢谢大哥

**Comment by EXsYang** [comment]
我上传的就是完整的啊，就是里面那些，哪里少？

**Comment by EXsYang** [comment]
想起来了，我把静态资源文件/static/ 放在Nginx代理了，这里确实没有，以补，你需要调整项目中的路由位置，我是按照Nginx代理配的，你改成路由到本地文件目录 \hspliving\hspliving-commodity\src\main\resources\static\，可能前端后端都要改
